apiVersion: v1
kind: Service
metadata:
  labels:
    run: jayne-new-pod
  name: flask-app
spec:
  ports:
  - port: 5500
    protocol: TCP
    targetPort: 5500
  selector:
    run: jayne-new-pod
  type: ClusterIP

