apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: flask-app
  name: jayne-flask-rs
spec:
  strategy:
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  selector:
    matchLabels:
      run: flask-app
  replicas: 3
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - image: eu.gcr.io/lbg-mea-17/jayne-task2-flaskapp:v3
        name: jayne-flask-app
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: db-cred
              key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jayne-flask-app
  name: flask-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask-app
  type: ClusterIP
