apiVersion: v1
# pod
kind: Pod
metadata:
#label must MATCH service selector (run:)
  labels:
    run: flask-app
  name: jayne-flask-pod
spec:
  containers:
  - image: eu.gcr.io/lbg-mea-17/jayne-task2-flaskapp:v1
    name: jayne-flask-app
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef:
          name: db-cred
          key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
#service
kind: Service
metadata:
  labels:
    run: jayne-flask-app
  name: flask-app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
# value MUST match pod label (run:)
  selector:
    run: flask-app
  type: ClusterIP
